# Generated by Django 4.1.3 on 2022-12-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admin'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin',
            field=models.CharField(choices=[('Y', 'Admin'), ('N', 'Not Admin ')], default='Y', max_length=1),
        ),
    ]
