# Generated by Django 4.1.3 on 2022-12-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_admin_options_alter_admin_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
