# Generated by Django 4.1.3 on 2022-12-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_media_media_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='classification',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='media',
            name='poster',
            field=models.ImageField(blank=True, upload_to='static/media/poster'),
        ),
    ]
