# Generated by Django 4.1.3 on 2022-12-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_movie_classification_alter_media_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
