# Generated by Django 4.1.3 on 2023-01-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_rename_added_in_media_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='title_img',
            field=models.ImageField(blank=True, upload_to='static/media/title'),
        ),
    ]
