# Generated by Django 4.1.3 on 2023-02-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_media_title_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='category',
            field=models.CharField(choices=[('N', 'Não Definido'), ('A', 'Ação'), ('AN', 'Animação'), ('AV', 'Aventura'), ('C', 'Comédia'), ('CR', 'Comédia Romântica'), ('D', 'Documentário'), ('F', 'Ficção Científica'), ('G', 'Guerra'), ('M', 'Musical'), ('R', 'Romance'), ('T', 'Terror'), ('MA', 'Marvel')], default='N', max_length=2),
        ),
    ]
