# Generated by Django 4.1.3 on 2023-02-16 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_alter_genre_category_alter_media_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='trailer',
            field=models.FileField(upload_to='static/media/trailer', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'h264'])]),
        ),
    ]
