# Generated by Django 4.1.3 on 2023-02-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_alter_media_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/banner'),
        ),
    ]
