# Generated by Django 4.1.3 on 2023-02-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_media_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='short_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
