# Generated by Django 4.1.4 on 2023-03-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_alter_user_managers_remove_user_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='img', upload_to='static/media/user'),
        ),
    ]
