# Generated by Django 4.1.3 on 2023-05-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
