# Generated by Django 4.1.3 on 2023-05-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0019_remove_user_name_alter_user_groups_alter_user_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/media/user'),
        ),
    ]
