# Generated by Django 4.1.3 on 2023-05-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0025_alter_user_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='category',
            field=models.CharField(choices=[('N', 'Não Definido'), ('A', 'Ação'), ('AN', 'Animação'), ('AV', 'Aventura'), ('C', 'Comédia'), ('CR', 'Comédia Romântica'), ('D', 'Documentário'), ('F', 'Ficção Científica'), ('G', 'Guerra'), ('M', 'Musical'), ('R', 'Romance'), ('T', 'Terror'), ('MA', 'Marvel'), ('C', 'Crime'), ('LA', 'Lançamento')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='classification',
            field=models.CharField(max_length=12),
        ),
    ]
