# Generated by Django 4.1.3 on 2023-06-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0026_alter_genre_category_alter_movie_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/poster'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
