# Generated by Django 4.1.3 on 2023-06-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0027_alter_media_poster_alter_media_title_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='poster',
            field=models.ImageField(blank=True, default=1, upload_to='static/media/poster'),
            preserve_default=False,
        ),
    ]
