# Generated by Django 4.1.3 on 2023-06-18 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0028_alter_media_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='title_img',
        ),
    ]
