# Generated by Django 4.1.3 on 2023-07-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0030_remove_movie_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
