# Generated by Django 4.1.3 on 2023-07-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0031_alter_media_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='category',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='media',
            name='banner',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='static/media/banner'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='poster',
            field=models.ImageField(blank=True, max_length=255, upload_to='static/media/poster'),
        ),
        migrations.AlterField(
            model_name='media',
            name='trailer',
            field=models.CharField(max_length=255),
        ),
    ]
