# Generated by Django 4.1.3 on 2023-08-03 03:03

import django.core.validators
from django.db import migrations
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0033_alter_media_media_file_alter_media_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=media.models.CustomFileField(max_length=255, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'h264'])]),
        ),
        migrations.AlterField(
            model_name='media',
            name='poster',
            field=media.models.CustomImageField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='trailer',
            field=media.models.CustomFileField(max_length=255, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'h264'])]),
        ),
    ]
