# Generated by Django 4.1.3 on 2023-08-03 03:37

import django.core.validators
from django.db import migrations
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0035_alter_media_media_file_alter_media_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='trailer',
            field=media.models.CustomTrailerField(max_length=255, upload_to='static/media/trailer', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'h264'])]),
        ),
    ]
